//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="Prueba.com.wsdl", ConfigurationName="PruebaSOAP")]
public interface PruebaSOAP
{
    
    // CODEGEN: Generating message contract since the wrapper namespace (urn:xmethods-delayed-quotes) of message pruebaRequest does not match the default value (Prueba.com.wsdl)
    [System.ServiceModel.OperationContractAttribute(Action="urn:xmethods-delayed-quotes#prueba", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
    pruebaResponse prueba(pruebaRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:xmethods-delayed-quotes#prueba", ReplyAction="*")]
    System.Threading.Tasks.Task<pruebaResponse> pruebaAsync(pruebaRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="prueba", WrapperNamespace="urn:xmethods-delayed-quotes", IsWrapped=true)]
public partial class pruebaRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string pruebaInput;
    
    public pruebaRequest()
    {
    }
    
    public pruebaRequest(string pruebaInput)
    {
        this.pruebaInput = pruebaInput;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="pruebaResponse", WrapperNamespace="urn:xmethods-delayed-quotes", IsWrapped=true)]
public partial class pruebaResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
    public string pruebaOutput;
    
    public pruebaResponse()
    {
    }
    
    public pruebaResponse(string pruebaOutput)
    {
        this.pruebaOutput = pruebaOutput;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface PruebaSOAPChannel : PruebaSOAP, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PruebaSOAPClient : System.ServiceModel.ClientBase<PruebaSOAP>, PruebaSOAP
{
    
    public PruebaSOAPClient()
    {
    }
    
    public PruebaSOAPClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PruebaSOAPClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PruebaSOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PruebaSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    pruebaResponse PruebaSOAP.prueba(pruebaRequest request)
    {
        return base.Channel.prueba(request);
    }
    
    public string prueba(string pruebaInput)
    {
        pruebaRequest inValue = new pruebaRequest();
        inValue.pruebaInput = pruebaInput;
        pruebaResponse retVal = ((PruebaSOAP)(this)).prueba(inValue);
        return retVal.pruebaOutput;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<pruebaResponse> PruebaSOAP.pruebaAsync(pruebaRequest request)
    {
        return base.Channel.pruebaAsync(request);
    }
    
    public System.Threading.Tasks.Task<pruebaResponse> pruebaAsync(string pruebaInput)
    {
        pruebaRequest inValue = new pruebaRequest();
        inValue.pruebaInput = pruebaInput;
        return ((PruebaSOAP)(this)).pruebaAsync(inValue);
    }
}
